### ISSUE TITLE
How to deal with multiple DB's in different versions

### ISSUE THREAD

**Issue by pulkownik1803** [OneIdentity/IdentityManager.PoSh#22]
I would like to have possibility to create connections to many DB's where those are in different versions. At the moment during importing module we have to point where dll's are. In my case those dll's can be different.

**Comment by akaer** [comment]
Hi @pulkownik1803,
thanks for raising the request. May you be able to describe your specific use case a little bit more? Having multiple database sessions with different versions might introduce several compatiblity issues. But will definitly look into it.

**Comment by pulkownik1803** [comment]
> Hi @pulkownik1803, thanks for raising the request. May you be able to describe your specific use case a little bit more? Having multiple database sessions with different versions might introduce several compatiblity issues. But will definitly look into it.

I'm preparing One Identity Manager for upgrade so I have DEV DB on version 8.2.1 and TEST DB on version 8.2. Those instances has different versions of DLL's. Tools for managing those two instances are installed in different locations to avoid AutoUpdate every time when connecting to second DB.
As I see, your module is creating set of cmdlet's (Get/Set/Update/Delete) for every object definition found in DB and this can lead to the errors due to the fact of the differences between object definitions.
I will move creation of the cmdlet's to time when session is created and as third parameter add path to the folder where tools are installed.

**Comment by pulkownik1803** [comment]
Hi @akaer I think I found the solution so I can share it with you. Please let me know if you are interested.

**Comment by akaer** [comment]
Hi @pulkownik1803, first of all, sorry for the late reply, but I have been busy with some other releases.
Yes, I would be interested in your work. Also, I've looked into this and at least come up with a solution for a simpler specification for the assembly loading. BUT as I already mentioned, using different databases with different DLL versions will cause compatibility issues. To really support this, the whole module would have to be rewritten. Basically, we would need different AppDomains in the same PowerShell session. And that is not something that is easy to implement in PowerShell. It's not impossible, but I don't really see a big benefit in supporting it.
