### ISSUE TITLE
New-Entity fails with error: "Resolve-Exception : The term 'Add-s' is not recognized as the name of a cmdlet..."

### ISSUE THREAD

**Issue by marahr** [OneIdentity/IdentityManager.PoSh#7]
New-Entity fails with the following error: "Resolve-Exception : The term 'Add-s' is not recognized as the name of a cmdlet..."

The line "$entity = Add-s -Entity $entity" in New-Entity.ps1 looks like a typo or an accidential paste. After removing that line an entity could be created.

**Comment by akaer** [comment]
Thanks for pointing that out. Fix is included.

**Comment by MatthiasBauer** [comment]
Closed
